// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	router "github.com/Willsem/golang-api-template/internal/http/router"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Routes provides a mock function with given fields:
func (_m *Handler) Routes() []router.Route {
	ret := _m.Called()

	var r0 []router.Route
	if rf, ok := ret.Get(0).(func() []router.Route); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]router.Route)
		}
	}

	return r0
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
