// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReadyStatus is an autogenerated mock type for the ReadyStatus type
type ReadyStatus struct {
	mock.Mock
}

// SetReady provides a mock function with given fields:
func (_m *ReadyStatus) SetReady() {
	_m.Called()
}

// NewReadyStatus creates a new instance of ReadyStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadyStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadyStatus {
	mock := &ReadyStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
