// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReadyStatus is an autogenerated mock type for the ReadyStatus type
type ReadyStatus struct {
	mock.Mock
}

// IsReady provides a mock function with given fields:
func (_m *ReadyStatus) IsReady() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewReadyStatus creates a new instance of ReadyStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadyStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadyStatus {
	mock := &ReadyStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
